### ISSUE TITLE
Failed build on Ubuntu

### ISSUE THREAD

**Issue by yphil-dev** [federicoiosue/omni-notes-desktop#20]
Hi! After installing the dependencies, I got the following error:

```
# cat /home/xxxxxx/.npm/_logs/2017-11-17T08_59_40_554Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/xxxxxx/.nvm/versions/node/v8.5.0/bin/node',
                1 verbose cli   '/home/xxxxxx/.nvm/versions/node/v8.5.0/bin/npm',
                1 verbose cli   'run',
                1 verbose cli   'package-linux' ]
2 info using npm@5.5.1
3 info using node@v8.5.0
4 verbose run-script [ 'prepackage-linux', 'package-linux', 'postpackage-linux' ]
5 info lifecycle omni-notes-desktop@0.0.4-SNAPSHOT~prepackage-linux: omni-notes-desktop@0.0.4-SNAPSHOT
6 info lifecycle omni-notes-desktop@0.0.4-SNAPSHOT~package-linux: omni-notes-desktop@0.0.4-SNAPSHOT
7 verbose lifecycle omni-notes-desktop@0.0.4-SNAPSHOT~package-linux: unsafe-perm in lifecycle true
8 verbose lifecycle omni-notes-desktop@0.0.4-SNAPSHOT~package-linux: PATH: /home/xxxxxx/.nvm/versions/node/v8.5.0/lib/node_modules/npm/bin/node-gyp-bin:/home/xxxxxx/src/omni-notes-desktop/node_modules/.bin:/home/xxxxxx/.nvm/versions/node/v8.5.0/bin:/home/xxxxxx/.cask/bin:/home/xxxxxx/.scripts:/home/xxxxxx/bin:/home/xxxxxx/bin:/home/xxxxxx/scripts:/home/xxxxxx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/xxxxxx/.rvm/bin
9 verbose lifecycle omni-notes-desktop@0.0.4-SNAPSHOT~package-linux: CWD: /home/xxxxxx/src/omni-notes-desktop
10 silly lifecycle omni-notes-desktop@0.0.4-SNAPSHOT~package-linux: Args: [ '-c',
                                                                            10 silly lifecycle   'electron-packager . --overwrite --platform=linux --arch=x64 --icon=icons/png/512x512.png --prune=true --out=dist --asar=true' ]
11 silly lifecycle omni-notes-desktop@0.0.4-SNAPSHOT~package-linux: Returned: code: 1  signal: null
12 info lifecycle omni-notes-desktop@0.0.4-SNAPSHOT~package-linux: Failed to exec package-linux script
13 verbose stack Error: omni-notes-desktop@0.0.4-SNAPSHOT package-linux: `electron-packager . --overwrite --platform=linux --arch=x64 --icon=icons/png/512x512.png --prune=true --out=dist --asar=true`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/xxxxxx/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/xxxxxx/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid omni-notes-desktop@0.0.4-SNAPSHOT
15 verbose cwd /home/xxxxxx/src/omni-notes-desktop
16 verbose Linux 4.4.0-98-lowlatency
17 verbose argv "/home/xxxxxx/.nvm/versions/node/v8.5.0/bin/node" "/home/xxxxxx/.nvm/versions/node/v8.5.0/bin/npm" "run" "package-linux"
18 verbose node v8.5.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error omni-notes-desktop@0.0.4-SNAPSHOT package-linux: `electron-packager . --overwrite --platform=linux --arch=x64 --icon=icons/png/512x512.png --prune=true --out=dist --asar=true`
22 error Exit status 1
23 error Failed at the omni-notes-desktop@0.0.4-SNAPSHOT package-linux script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Platform details:

```
Linux xxxxxx 4.4.0-98-lowlatency #121-Ubuntu SMP PREEMPT Tue Oct 10 15:16:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yphil-dev** [comment]
Never mind, it works now :)
